version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/config/docker/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54322:5432
  # redis:
  #   container_name: redis
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
