jwtSecret: arsht934n2132smatn289381niraesnt923
clientId: app2
clientSecret: straarstarststrastrcxdzxcrstarsttwparstarstwqdqwfpat
targetUrl: http://127.0.0.1:5002
scopes:
  - openid
  - email
localUrl: http://127.0.0.1:3002/api
oidcUrl: http://localhost:3000/oidc
